{% set name = "pyRXP" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24ba90a2354f64f8ce8cacdc6c6f328157ff74d2ef143e91ccae653df8008194

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    # extras for cross compiling
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pip
    - psutil
  source_files:
    - test/
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python test/runAll.py

about:
  home: http://www.reportlab.com
  dev_url: https://bitbucket.org/rptlab/pyrxp/
  license: ReportLab BSD derived
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python RXP interface - fast validating XML parser

extra:
  recipe-maintainers:
    - duncanmmacleod
