{% set name = "pyRXP" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad7c244db9dd1c15541af059d6ea58a7f3e533979abe8184a20848152477108e
  patches:
    # remove existing egg-info directory, and add license
    - clean-up-tarball.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyRXPU

about:
  home: http://www.reportlab.com
  dev_url: https://bitbucket.org/rptlab/pyrxp/
  license: ReportLab BSD derived
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python RXP interface - fast validating XML parser

extra:
  recipe-maintainers:
    - duncanmmacleod
