{% set name = "pyRXP" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5563dee342f329f840380aafccf786b504d6a82e91611defb27f3f51043be9a

build:
  error_overdepending: true
  ignore_run_exports:
    - ucrt  # [win]
    - vc14_runtime  # [win]
  number: 4
  script:
    - if exist "pyRXP.egg-info\SOURCES.txt" del "pyRXP.egg-info\SOURCES.txt"  # [win]
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl != 'cpython']

requirements:
  build:
    - {{ compiler('c') }}
    # extras for cross compiling
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pip
    - psutil
  source_files:
    - test/
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python test/runAll.py

about:
  home: http://www.reportlab.com
  doc_url: https://pyrxp.readthedocs.io/en/latest/usage.html
  license: ReportLab BSD derived
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python RXP interface - fast validating XML parser

extra:
  recipe-maintainers:
    - duncanmmacleod
